import Foundation

/// Decoded shape of `meeting_transcripts.chapters_json` (snake_case keys,
/// shared with Go's `internal/meeting.ChaptersResult`). Generated by the
/// `meeting.chapters` prompt — automatically after save when segments exist,
/// or via the Recap tab's "Generate chapters" button.
package struct MeetingChapters: Codable, Equatable {
    package var overallSummary: String
    package var chapters: [MeetingChapter]

    package enum CodingKeys: String, CodingKey {
        case overallSummary = "overall_summary"
        case chapters
    }

    package init(overallSummary: String, chapters: [MeetingChapter]) {
        self.overallSummary = overallSummary
        self.chapters = chapters
    }

    package init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        overallSummary = try c.decodeIfPresent(String.self, forKey: .overallSummary) ?? ""
        chapters = try c.decodeIfPresent([MeetingChapter].self, forKey: .chapters) ?? []
    }

    /// nil for malformed JSON or an empty chapters array — callers then fall
    /// back to the flat recap rendering (legacy behavior), mirroring
    /// `TranscriptSegments.decode`.
    package static func decode(_ json: String) -> Self? {
        guard let data = json.data(using: .utf8),
              let decoded = try? JSONDecoder().decode(Self.self, from: data),
              !decoded.chapters.isEmpty else {
            return nil
        }
        return decoded
    }

    /// Deterministic encoding (sorted keys) so repeated converted-item writes
    /// produce stable JSON (the `TranscriptSegments.encode` precedent).
    package static func encode(_ chapters: Self) -> String? {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        guard let data = try? encoder.encode(chapters) else { return nil }
        return String(data: data, encoding: .utf8)
    }

    /// Chapter → transcript jump resolution: the idx of the first non-deleted
    /// utterance starting at or after `startSec`; when the chapter starts
    /// after the last utterance, the last non-deleted one (so the jump still
    /// lands somewhere sensible). nil when every utterance is deleted.
    package static func firstUtteranceIdx(in utterances: [TranscriptUtterance], atOrAfter startSec: Double) -> Int? {
        let visible = utterances.filter { !$0.deleted }
        if let hit = visible.first(where: { $0.startSec >= startSec }) {
            return hit.idx
        }
        return visible.last?.idx
    }
}

/// One chapter of a meeting: a contiguous time range with per-chapter
/// extractions. All fields decode tolerantly (a partial AI payload renders
/// with empty groups instead of failing the whole decode).
package struct MeetingChapter: Codable, Equatable {
    package var title: String
    package var startSec: Double
    package var endSec: Double
    package var participants: [String]
    package var summary: String
    package var decisions: [String]
    package var actionItems: [ChapterActionItem]
    package var openQuestions: [String]

    package enum CodingKeys: String, CodingKey {
        case title
        case startSec = "start_sec"
        case endSec = "end_sec"
        case participants
        case summary
        case decisions
        case actionItems = "action_items"
        case openQuestions = "open_questions"
    }

    package init(
        title: String,
        startSec: Double,
        endSec: Double,
        participants: [String] = [],
        summary: String = "",
        decisions: [String] = [],
        actionItems: [ChapterActionItem] = [],
        openQuestions: [String] = []
    ) {
        self.title = title
        self.startSec = startSec
        self.endSec = endSec
        self.participants = participants
        self.summary = summary
        self.decisions = decisions
        self.actionItems = actionItems
        self.openQuestions = openQuestions
    }

    package init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        title = try c.decodeIfPresent(String.self, forKey: .title) ?? ""
        startSec = try c.decodeIfPresent(Double.self, forKey: .startSec) ?? 0
        endSec = try c.decodeIfPresent(Double.self, forKey: .endSec) ?? 0
        participants = try c.decodeIfPresent([String].self, forKey: .participants) ?? []
        summary = try c.decodeIfPresent(String.self, forKey: .summary) ?? ""
        decisions = try c.decodeIfPresent([String].self, forKey: .decisions) ?? []
        actionItems = try c.decodeIfPresent([ChapterActionItem].self, forKey: .actionItems) ?? []
        openQuestions = try c.decodeIfPresent([String].self, forKey: .openQuestions) ?? []
    }
}

/// One action item inside a chapter. `convertedTargetID` is stamped when the
/// item is converted into a Target — a link, not a delete (DASH-03 spirit);
/// see `MeetingTranscriptQueries.convertActionItemToTarget`. Decodes from both
/// the persisted object form and a bare string (mirrors Go's
/// `ChapterActionItem.UnmarshalJSON`).
package struct ChapterActionItem: Codable, Equatable {
    package var text: String
    package var convertedTargetID: Int64?

    package enum CodingKeys: String, CodingKey {
        case text
        case convertedTargetID = "converted_target_id"
    }

    package init(text: String, convertedTargetID: Int64? = nil) {
        self.text = text
        self.convertedTargetID = convertedTargetID
    }

    package init(from decoder: Decoder) throws {
        if let single = try? decoder.singleValueContainer(),
           let bare = try? single.decode(String.self) {
            text = bare
            convertedTargetID = nil
            return
        }
        let c = try decoder.container(keyedBy: CodingKeys.self)
        text = try c.decodeIfPresent(String.self, forKey: .text) ?? ""
        convertedTargetID = try c.decodeIfPresent(Int64.self, forKey: .convertedTargetID)
    }
}
