import Foundation

/// Structured running summary generated by AI as part of channel digest.
/// Stored as JSON in the `running_summary` column of `digests`.
package struct RunningSummary: Codable, Equatable {
    package let activeTopics: [ActiveTopic]?
    package let recentDecisions: [RecentDecision]?
    package let channelDynamics: String?
    package let openQuestions: [String]?
    package let meta: Meta?

    package enum CodingKeys: String, CodingKey {
        case activeTopics = "active_topics"
        case recentDecisions = "recent_decisions"
        case channelDynamics = "channel_dynamics"
        case openQuestions = "open_questions"
        case meta
    }

    package struct Meta: Codable, Equatable {
        package let generatedAt: String?
        package let digestID: String?
        package let messageCount: Int?
        package let period: String?

        enum CodingKeys: String, CodingKey {
            case generatedAt = "generated_at"
            case digestID = "digest_id"
            case messageCount = "message_count"
            case period
        }
    }
}

package struct ActiveTopic: Codable, Equatable, Identifiable {
    package var id: String { topic }

    package let topic: String
    package let status: String?
    package let started: String?
    package let lastUpdate: String?
    package let keyParticipants: [String]?
    package let summary: String?

    package enum CodingKeys: String, CodingKey {
        case topic, status, started, summary
        case lastUpdate = "last_update"
        case keyParticipants = "key_participants"
    }
}

package struct RecentDecision: Codable, Equatable, Identifiable {
    package var id: String { decision + (date ?? "") }

    package let decision: String
    package let date: String?
    package let by: String?
    package let status: String?
}
