import Foundation

/// Structured running summary generated by AI as part of channel digest.
/// Stored as JSON in the `running_summary` column of `digests`.
public struct RunningSummary: Codable, Equatable {
    public let activeTopics: [ActiveTopic]?
    public let recentDecisions: [RecentDecision]?
    public let channelDynamics: String?
    public let openQuestions: [String]?
    public let meta: Meta?

    public enum CodingKeys: String, CodingKey {
        case activeTopics = "active_topics"
        case recentDecisions = "recent_decisions"
        case channelDynamics = "channel_dynamics"
        case openQuestions = "open_questions"
        case meta
    }

    public struct Meta: Codable, Equatable {
        public let generatedAt: String?
        public let digestID: String?
        public let messageCount: Int?
        public let period: String?

        enum CodingKeys: String, CodingKey {
            case generatedAt = "generated_at"
            case digestID = "digest_id"
            case messageCount = "message_count"
            case period
        }
    }
}

public struct ActiveTopic: Codable, Equatable, Identifiable {
    public var id: String { topic }

    public let topic: String
    public let status: String?
    public let started: String?
    public let lastUpdate: String?
    public let keyParticipants: [String]?
    public let summary: String?

    public enum CodingKeys: String, CodingKey {
        case topic, status, started, summary
        case lastUpdate = "last_update"
        case keyParticipants = "key_participants"
    }
}

public struct RecentDecision: Codable, Equatable, Identifiable {
    public var id: String { decision + (date ?? "") }

    public let decision: String
    public let date: String?
    public let by: String?
    public let status: String?
}
