import Foundation
import GRDB

// MARK: - TargetSubItem

public struct TargetSubItem: Codable, Identifiable, Equatable {
    public let id = UUID()
    public var text: String
    public var done: Bool
    public var dueDate: String?

    // Explicit public replacement for the (never-public) synthesized memberwise init.
    public init(text: String, done: Bool, dueDate: String? = nil) {
        self.text = text
        self.done = done
        self.dueDate = dueDate
    }

    enum CodingKeys: String, CodingKey {
        case text, done
        case dueDate = "due_date"
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.text == rhs.text && lhs.done == rhs.done && lhs.dueDate == rhs.dueDate
    }

    public var dueDateParsed: Date? {
        guard let dueDate, !dueDate.isEmpty else { return nil }
        return Target.parseDueDate(dueDate)
    }

    public var isOverdue: Bool {
        guard !done, let date = dueDateParsed, let dueDate else { return false }
        if Target.isDateOnly(dueDate) {
            // Same "due ON the day" semantics as Target.isOverdue.
            return dueDate < Target.todayDayString()
        }
        return date < Date()
    }
}

// MARK: - TargetNote

public struct TargetNote: Codable, Identifiable, Equatable {
    public let id = UUID()
    public var text: String
    public var createdAt: String

    // Explicit public replacement for the (never-public) synthesized memberwise init.
    public init(text: String, createdAt: String) {
        self.text = text
        self.createdAt = createdAt
    }

    enum CodingKeys: String, CodingKey {
        case text
        case createdAt = "created_at"
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.text == rhs.text && lhs.createdAt == rhs.createdAt
    }

    private static let iso8601Formatter: ISO8601DateFormatter = {
        let fmt = ISO8601DateFormatter()
        fmt.formatOptions = [.withInternetDateTime]
        return fmt
    }()

    public var createdDate: Date? {
        Self.iso8601Formatter.date(from: createdAt)
    }
}

// MARK: - TargetNextStep

/// AI-suggested single next action for a target, decoded from the `next_step`
/// JSON column. Generated by the Go next-step pipeline / `tasks next-step` CLI.
public struct TargetNextStep: Codable, Equatable {
    public var title: String
    public var rationale: String
    public var urgency: String          // "deadline" | "blocked" | "stale" | "normal"
    public var urgencyDetail: String
    public var actions: [TargetNextStepAction]

    enum CodingKeys: String, CodingKey {
        case title, rationale, urgency
        case urgencyDetail = "urgency_detail"
        case actions
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        title = (try? c.decode(String.self, forKey: .title)) ?? ""
        rationale = (try? c.decode(String.self, forKey: .rationale)) ?? ""
        urgency = (try? c.decode(String.self, forKey: .urgency)) ?? "normal"
        urgencyDetail = (try? c.decode(String.self, forKey: .urgencyDetail)) ?? ""
        actions = (try? c.decode([TargetNextStepAction].self, forKey: .actions)) ?? []
    }
}

/// One button on the next-step card. `kind` selects how the UI wires it.
public struct TargetNextStepAction: Codable, Equatable, Identifiable {
    public var label: String
    public var kind: String             // "assistant" | "open_links" | "mark_done" | "dismiss"
    public var prompt: String?

    public var id: String { label + kind }
}

// MARK: - Target

public struct Target: FetchableRecord, TableRecord, Codable, Identifiable, Equatable, Hashable {
    public static let databaseTableName = "targets"

    public let id: Int
    public let text: String
    public let intent: String
    public let level: String           // "quarter", "month", "week", "day", "custom"
    public let customLabel: String     // free text only when level='custom'
    public let periodStart: String     // YYYY-MM-DD
    public let periodEnd: String       // YYYY-MM-DD
    public let parentId: Int?
    public let status: String          // "todo", "in_progress", "blocked", "done", "dismissed", "snoozed"
    public let priority: String        // "high", "medium", "low"
    public let ownership: String       // "mine", "delegated", "watching"
    public let ballOn: String
    public let dueDate: String         // "YYYY-MM-DDTHH:MM" or ""
    public let snoozeUntil: String
    public let blocking: String
    public let tags: String            // JSON []
    public let subItems: String        // JSON []
    public let notes: String           // JSON []
    public let progress: Double        // 0.0..1.0
    public let sourceType: String      // "extract","briefing","manual","chat","inbox","jira","slack"
    public let sourceID: String
    public let aiLevelConfidence: Double?
    public let createdAt: String
    public let updatedAt: String
    public let nextStep: String        // JSON, "" when not yet generated
    public let nextStepAt: String      // when nextStep was generated

    enum CodingKeys: String, CodingKey {
        case id
        case text
        case intent
        case level
        case customLabel      = "custom_label"
        case periodStart      = "period_start"
        case periodEnd        = "period_end"
        case parentId         = "parent_id"
        case status
        case priority
        case ownership
        case ballOn           = "ball_on"
        case dueDate          = "due_date"
        case snoozeUntil      = "snooze_until"
        case blocking
        case tags
        case subItems = "sub_items"
        case notes
        case progress
        case sourceType       = "source_type"
        case sourceID         = "source_id"
        case aiLevelConfidence = "ai_level_confidence"
        case createdAt        = "created_at"
        case updatedAt        = "updated_at"
        case nextStep         = "next_step"
        case nextStepAt       = "next_step_at"
    }

    public init(row: Row) {
        id               = row["id"]
        text             = row["text"] ?? ""
        intent           = row["intent"] ?? ""
        level            = row["level"] ?? "day"
        customLabel      = row["custom_label"] ?? ""
        periodStart      = row["period_start"] ?? ""
        periodEnd        = row["period_end"] ?? ""
        parentId         = row["parent_id"]
        status           = row["status"] ?? "todo"
        priority         = row["priority"] ?? "medium"
        ownership        = row["ownership"] ?? "mine"
        ballOn           = row["ball_on"] ?? ""
        dueDate          = row["due_date"] ?? ""
        snoozeUntil      = row["snooze_until"] ?? ""
        blocking         = row["blocking"] ?? ""
        tags             = row["tags"] ?? "[]"
        subItems         = row["sub_items"] ?? "[]"
        notes            = row["notes"] ?? "[]"
        progress         = row["progress"] ?? 0.0
        sourceType       = row["source_type"] ?? "manual"
        sourceID         = row["source_id"] ?? ""
        aiLevelConfidence = row["ai_level_confidence"]
        createdAt        = row["created_at"] ?? ""
        updatedAt        = row["updated_at"] ?? ""
        nextStep         = row["next_step"] ?? ""
        nextStepAt       = row["next_step_at"] ?? ""
    }

    // MARK: - Hashable (id-based)

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }

    // MARK: - Status Predicates

    public var isActive: Bool {
        ["todo", "in_progress", "blocked"].contains(status)
    }

    public var isOverdue: Bool {
        guard isActive, !dueDate.isEmpty else { return false }
        guard let due = Self.parseDueDate(dueDate) else { return false }
        if Self.isDateOnly(dueDate) {
            // Date-only means "due ON that day": overdue only once the user's
            // local day has passed, never mid-day just because the value
            // parses as UTC midnight (which lies behind `Date()` for most of
            // the day west of UTC).
            return dueDate < Self.todayDayString()
        }
        return due < Date()
    }

    public var isDueToday: Bool {
        guard !dueDate.isEmpty else { return false }
        guard let due = Self.parseDueDate(dueDate) else { return false }
        if Self.isDateOnly(dueDate) {
            // Compare local calendar days — the stored day IS the due day.
            return dueDate == Self.todayDayString()
        }
        return Calendar.current.isDateInToday(due)
    }

    /// True for date-only stored values ("YYYY-MM-DD", no time component).
    public static func isDateOnly(_ stored: String) -> Bool {
        !stored.contains("T")
    }

    /// Today's calendar day in the USER'S timezone as "yyyy-MM-dd" —
    /// lexicographically comparable with stored date-only due dates.
    /// Local, not UTC: "due today" must match the day on the user's wall
    /// clock, east and west of UTC alike.
    public static func todayDayString(now: Date = Date()) -> String {
        localDayFormatter.string(from: now)
    }

    private static let localDayFormatter: DateFormatter = {
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd"
        fmt.locale = Locale(identifier: "en_US_POSIX")
        fmt.timeZone = TimeZone.current
        return fmt
    }()

    // MARK: - Level

    public var levelOrder: Int {
        switch level {
        case "quarter": return 0
        case "month":   return 1
        case "week":    return 2
        case "day":     return 3
        default:        return 4
        }
    }

    // MARK: - Priority

    public var priorityOrder: Int {
        switch priority {
        case "high":   return 0
        case "medium": return 1
        case "low":    return 2
        default:       return 1
        }
    }

    // MARK: - Status Display

    public var statusIcon: String {
        switch status {
        case "todo":       return "circle"
        case "in_progress": return "circle.dotted.circle"
        case "blocked":    return "exclamationmark.circle"
        case "done":       return "checkmark.circle.fill"
        case "dismissed":  return "xmark.circle"
        case "snoozed":    return "moon.circle"
        default:           return "circle"
        }
    }

    public var statusColor: String {
        switch status {
        case "todo":       return "secondary"
        case "in_progress": return "blue"
        case "blocked":    return "red"
        case "done":       return "green"
        case "dismissed":  return "gray"
        case "snoozed":    return "purple"
        default:           return "secondary"
        }
    }

    // MARK: - JSON Decoders

    public var decodedTags: [String] {
        guard !tags.isEmpty, tags != "[]",
              let data = tags.data(using: .utf8) else { return [] }
        return (try? JSONDecoder().decode([String].self, from: data)) ?? []
    }

    public var decodedSubItems: [TargetSubItem] {
        guard !subItems.isEmpty, subItems != "[]",
              let data = subItems.data(using: .utf8) else { return [] }
        return (try? JSONDecoder().decode([TargetSubItem].self, from: data)) ?? []
    }

    public var decodedNotes: [TargetNote] {
        guard !notes.isEmpty, notes != "[]",
              let data = notes.data(using: .utf8) else { return [] }
        return (try? JSONDecoder().decode([TargetNote].self, from: data)) ?? []
    }

    /// Decoded AI next-step suggestion, or nil when none has been generated.
    public var decodedNextStep: TargetNextStep? {
        guard !nextStep.isEmpty, let data = nextStep.data(using: .utf8) else { return nil }
        guard let ns = try? JSONDecoder().decode(TargetNextStep.self, from: data),
              !ns.title.isEmpty else { return nil }
        return ns
    }

    /// Progress as "2/5" format, nil if no sub-items.
    public var subItemsProgress: String? {
        let items = decodedSubItems
        guard !items.isEmpty else { return nil }
        let done = items.filter(\.done).count
        return "\(done)/\(items.count)"
    }

    // MARK: - Source Helpers

    public var sourceTrackID: Int? {
        guard sourceType == "track" else { return nil }
        return Int(sourceID)
    }

    public var sourceDigestID: Int? {
        guard sourceType == "digest" else { return nil }
        return Int(sourceID)
    }

    public var sourceBriefingID: Int? {
        guard sourceType == "briefing" else { return nil }
        return Int(sourceID)
    }

    // MARK: - Date Helpers

    /// UTC storage formatter for due dates: the Go side writes `t.UTC()` and
    /// compares against `now.UTC()` (cmd/remind.go, NotifyDueTargets), so the
    /// stored wall time is UTC — never parse/format it in the local zone.
    private static let datetimeFormatter: DateFormatter = {
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd'T'HH:mm"
        fmt.locale = Locale(identifier: "en_US_POSIX")
        fmt.timeZone = TimeZone(identifier: "UTC")
        return fmt
    }()

    /// UTC date-only formatter for period bounds (stored as plain "YYYY-MM-DD").
    private static let periodFormatter: DateFormatter = {
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd"
        fmt.locale = Locale(identifier: "en_US_POSIX")
        fmt.timeZone = TimeZone(identifier: "UTC")
        return fmt
    }()

    /// Expands a target's period to the natural bounds of `level`, anchored on the
    /// existing `period_start` so the target keeps its "when" while the period
    /// reflects the new horizon granularity:
    ///   day → the anchor day; week → Mon–Sun of the anchor's week;
    ///   month → 1st–last of the anchor's month; quarter → the anchor's quarter.
    /// Returns nil for "custom" (and unknown levels / malformed anchors), whose
    /// period is user-defined and must not be overwritten.
    public static func periodWindow(for level: String, anchoredOn periodStart: String) -> (start: String, end: String)? {
        guard let anchor = periodFormatter.date(from: periodStart) else { return nil }
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = TimeZone(identifier: "UTC") ?? cal.timeZone
        cal.firstWeekday = 2 // Monday

        // Last day of the calendar unit (.weekOfYear/.month) containing `anchor`.
        func bounds(_ unit: Calendar.Component) -> (Date, Date)? {
            guard let interval = cal.dateInterval(of: unit, for: anchor),
                  let end = cal.date(byAdding: .day, value: -1, to: interval.end) else { return nil }
            return (interval.start, end)
        }

        let range: (Date, Date)?
        switch level {
        case "day":
            range = (anchor, anchor)
        case "week":
            range = bounds(.weekOfYear)
        case "month":
            range = bounds(.month)
        case "quarter":
            // Compute manually — Calendar's .quarter component is unreliable.
            let month = cal.component(.month, from: anchor)
            let year = cal.component(.year, from: anchor)
            let startMonth = ((month - 1) / 3) * 3 + 1
            let startComps = DateComponents(year: year, month: startMonth, day: 1)
            let lastMonthComps = DateComponents(year: year, month: startMonth + 2, day: 1)
            if let start = cal.date(from: startComps),
               let lastMonthFirst = cal.date(from: lastMonthComps),
               let lastMonth = cal.dateInterval(of: .month, for: lastMonthFirst),
               let end = cal.date(byAdding: .day, value: -1, to: lastMonth.end) {
                range = (start, end)
            } else {
                range = nil
            }
        default:
            range = nil
        }

        guard let (start, end) = range else { return nil }
        return (periodFormatter.string(from: start), periodFormatter.string(from: end))
    }

    /// Parses a stored due date ("YYYY-MM-DDTHH:MM" or "YYYY-MM-DD", both UTC)
    /// into the instant it denotes; date-only values parse as UTC midnight.
    public static func parseDueDate(_ str: String) -> Date? {
        if let d = datetimeFormatter.date(from: str) { return d }
        if let d = periodFormatter.date(from: str) { return d }
        return nil
    }

    /// Formats due date for storage: "yyyy-MM-dd'T'HH:mm" in UTC.
    public static func formatDueDate(_ date: Date) -> String {
        datetimeFormatter.string(from: date)
    }

    private static let iso8601WithFractional: ISO8601DateFormatter = {
        let fmt = ISO8601DateFormatter()
        fmt.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return fmt
    }()

    private static let iso8601Standard: ISO8601DateFormatter = {
        let fmt = ISO8601DateFormatter()
        fmt.formatOptions = [.withInternetDateTime]
        return fmt
    }()

    public var createdDate: Date {
        if let date = Self.iso8601WithFractional.date(from: createdAt) { return date }
        return Self.iso8601Standard.date(from: createdAt) ?? Date()
    }

    public var updatedDate: Date {
        if let date = Self.iso8601WithFractional.date(from: updatedAt) { return date }
        return Self.iso8601Standard.date(from: updatedAt) ?? Date()
    }

    public var dueDateFormatted: String? {
        guard !dueDate.isEmpty,
              let date = Self.parseDueDate(dueDate) else { return nil }
        let display = DateFormatter()
        display.dateStyle = .medium
        if dueDate.contains("T") {
            // Stored-UTC instant, shown converted to the local zone.
            display.timeStyle = .short
        } else {
            // Date-only due dates carry no meaningful time: show the stored
            // calendar day as-is (UTC) instead of shifting it into local.
            display.timeStyle = .none
            display.timeZone = TimeZone(identifier: "UTC")
        }
        return display.string(from: date)
    }

    public var dueDateParsed: Date? {
        guard !dueDate.isEmpty else { return nil }
        return Self.parseDueDate(dueDate)
    }
}
