; Nim definitions, written for Watchtower (tree-sitter-nim ships no
; tags.scm; spec §6.3). `proc`, `func`, `iterator` and `converter` are
; functions, `method` a method (its container the type of its first
; parameter, set in Go), `template` and `macro` macros. A type is an enum,
; a struct for `object` and `tuple`, a class for `ref object`, an
; interface for a `concept`, any other a type (decided in Go); enum
; values are consts, object fields fields. `const` and `let` names are
; consts, `var` names vars. A name keeps no export marker (`add*` gives
; add). Definitions inside a routine body are locals (dropped in Go).
; Docs are `##` comments where Nim puts them (read in Go): the first in
; a routine or a type body, else one trailing on the definition's line.
;
; Limits: `#` comments are not docs; operators in backticks, routines
; and types generated by templates or macros, `when` branches and object
; variants' branch fields are not indexed.

(proc_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]) @definition.function

(func_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]) @definition.function

(iterator_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]) @definition.function

(converter_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]) @definition.function

(method_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]) @definition.method

(template_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]) @definition.macro

(macro_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]) @definition.macro

(type_declaration (type_symbol_declaration name: [(identifier) @name (exported_symbol (identifier) @name)])) @definition.type

(enum_field_declaration (symbol_declaration name: [(identifier) @name (exported_symbol (identifier) @name)])) @definition.const

(field_declaration (symbol_declaration_list (symbol_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]))) @definition.field

(const_section (variable_declaration (symbol_declaration_list (symbol_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]))) @definition.const)

(let_section (variable_declaration (symbol_declaration_list (symbol_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]))) @definition.const)

(var_section (variable_declaration (symbol_declaration_list (symbol_declaration name: [(identifier) @name (exported_symbol (identifier) @name)]))) @definition.var)
