-- +goose Up
-- Communication style profile: an AI-distilled, user-editable description of
-- how the owner writes on Slack. Consumed by the situation Discuss chat when
-- drafting replies. Generated by `watchtower inbox style-sample`, edited in
-- the Desktop Profile tab.
ALTER TABLE workspace ADD COLUMN style_profile TEXT NOT NULL DEFAULT '';
ALTER TABLE workspace ADD COLUMN style_profile_updated_at TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE workspace DROP COLUMN style_profile_updated_at;
ALTER TABLE workspace DROP COLUMN style_profile;
