package digest

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

// allowedStrongSource is one deliberately-strong entry in the tier-routing
// property scan's allowlist below: a source tag that reaches a
// digest.Generator's Generate method but is not in TierForSource's light
// switch, on purpose. reason is mandatory (checked at the top of the test) —
// an entry with no reason is exactly the "next person silences the scan by
// appending a bare line" failure mode this shape exists to prevent.
type allowedStrongSource struct {
	tag    string
	reason string
}

// allowedStrongSources is every source tag TestTierForSource_EveryGenerateCallIsTagged
// finds reaching Generate that is NOT in TierForSource's light-tier switch,
// acknowledged as deliberate. Adding a line here is a real decision, not a
// rubber stamp — it must name why the source stays on the strong (expensive)
// tier by default, citing the code comment / CLAUDE.md / inventory doc / fix
// wave that already made the call, or an explicit new owner decision. A call
// site that lands here for a made-up reason is exactly the failure mode this
// test exists to catch: reviewers should read a new line here the same way
// they'd read an edit to TierForSource's switch itself.
//
// This list was assembled from the fix-wave-4 task-6 tier census
// (.superpowers/sdd/2026-09-13-audit-fix-wave4/verify-tiers.md §2/§4): every
// tagged-but-unlisted source that stays strong, plus the untagged call sites
// this same task tagged (tag-only — their tier did not change).
var allowedStrongSources = []allowedStrongSource{
	// Already tagged before this task, deliberately strong (verify-tiers.md
	// §4 "no change" tables — several already say so in their own code
	// comments):
	{"people.reduce", "per-person weekly synthesis from raw messages/stats into a people-card narrative"},
	{"people.team", "team-level roll-up across all people cards"},
	{"day_plan.generate", "synthesizes calendar/targets/Jira/people/memory into a scheduled plan; decision 9 gives it backoff, not a tier change"},
	{"inbox.compose", "clusters triaged signals into dashboard situations (CLAUDE.md: situation cards run 'strong model tier', compose sits in the same narrative-synthesis stage)"},
	{"inbox.situation_card", "CLAUDE.md: situation cards generated 'via a stronger model'"},
	{"inbox.style_sample", "CLAUDE.md: 'Style profile generated by watchtower inbox style-sample (inbox.style_sample, strong tier)'"},
	{"memory.render_map", "worldmap.go: explicitly strong by design — a judgment call about what's worth surfacing in the hot summary"},
	{"memory.revise_beliefs", "beliefs.go: 'strong-tier belief-revision proposer... strong route by absence from the light switch'"},
	{"memory.reflect", "reflect.go: explicitly strong by design — weekly meta-pass over vault churn"},
	{"memory.entity_rewrite", "rewrite.go: explicitly strong by design — page-level prose rewrite"},
	{"targets.link", "proposes parent/secondary links against up to 100 active targets — a judgment call, not mechanical rule derivation"},
	{"targets.next_step", "nextstep.go: 'routes to the default (quality) model since it requires prioritisation reasoning'; decision 9 gives it backoff, not a tier change"},
	{"digest.daily", "cross-channel daily rollup; decision 9's frequency fix (once/day) addresses cost here, not tier"},
	{"digest.weekly", "same class as digest.daily; also dead code today (RunWeeklyTrends has no callers) — tier is moot but still a real switch entry"},
	{"digest.channel", "single high-activity channel digest; digest.channel vs digest.channel_batch is a real inconsistency flagged as an open owner question, out of scope for fix wave 4 (task-6-brief.md ruling) — do not resolve it by editing this allowlist"},
	{"customtrack.run", "full per-track scan/dispatch deciding what's worth surfacing from new activity"},
	{"tracks.extract_batch", "auto-tracks narrative extraction across a batch of channels — same class as digest.daily"},
	{"briefing.daily", "full daily-briefing synthesis across every pipeline; decision 9 backoff applies, not a tier change"},
	{"meeting.chapters", "models_test.go: 'meeting.chapters routes strong by absence... only the followup drafts are light'"},
	{"ideas.consolidate", "stage-2 dedupe/merge/decision-making over the whole ideas registry — the judgment layer over mechanical stage-1 mining"},
	{"catchup.compose", "CLAUDE.md: 'One strong-tier catchup.compose call composes eight gathered window areas'"},

	// Newly tagged by fix-wave-4 task 6 (previously untagged, logged
	// source:"unknown"): tag-only per decision 9 — attribution fixed, tier
	// unchanged (verify-tiers.md §3/§4 Census B).
	{"meeting.recap", "full recap synthesis (decisions/action items/open questions/ideas) from a transcript — audit M-4: 'the meeting ones are probably intended strong'"},
	{"meeting.prep", "attendee/Jira/memory/profile synthesis into a meeting-prep brief — same class as meeting.recap"},
	{"meeting.notes", "publishable markdown notes from a transcript with recap context — same class as meeting.recap"},
	{"meeting.extract_topics", "splits raw pasted text into discussion topics — judgment over arbitrary text; low-frequency, owner-invoked, not a hot loop"},
	{"tasks.generate", "CLI 'targets generate' — extracts a target list from free text, judgment-heavy, low-frequency owner-invoked action"},
	{"tasks.update", "CLI 'targets update' — applies a free-text instruction to a target's fields, judgment-heavy, low-frequency owner-invoked action"},
	{"prompts.tune", "meta-call that reruns whichever prompt is being tuned, itself invoked only by the owner (watchtower prompts tune); the highest-quality model is the right default for something that rewrites a live prompt template"},
}

// skipGenerateCallFiles are decorator implementations of digest.Generator
// that forward whatever ctx they were handed unchanged (PooledGenerator,
// timeoutGenerator) — the source tag, if any, was already applied by the
// caller before it reached the decorator. They are not new AI-call
// origination points, so the scan does not require them to re-tag.
var skipGenerateCallFiles = map[string]bool{
	filepath.Join("internal", "digest", "pooled.go"):            true,
	filepath.Join("internal", "digest", "timeout_generator.go"): true,
}

// TestTierForSource_EveryGenerateCallIsTagged is a property scan, not an
// enumeration: it walks every non-test .go file under internal/ and cmd/,
// finds every call to a digest.Generator's Generate method, and requires
// that (a) the context it is given carries a digest.WithSource tag and (b)
// that tag either routes light via TierForSource or is named, with a reason,
// in allowedStrongSources above. A brand-new call site that skips tagging
// entirely, or that tags itself with a source nobody has classified, fails
// this test the day it is written — that is the whole point (a prior fix
// wave's enumeration guard missed exactly this shape of new call site; see
// CLAUDE.md's note on wave 3's guard-perechislenie replacement).
//
// This subsumes TestTierForSource above, which still pins the tier of named
// tags; this test pins completeness of coverage instead — a different
// property.
//
// Implementation is a deliberately narrow syntactic approximation, not a
// full type-checked call graph: it resolves a tag expression to a literal
// string via (1) a string literal, (2) a same/cross-package const (single or
// multi-hop, e.g. `const reviseSource = prompts.MemoryReviseBeliefs`), or (3)
// two hand-verified dynamic exceptions (see resolveTagExprToStrings) for the
// only two non-constant tag expressions that exist in the repo today. Any
// call or expression shape this scanner does not recognize fails LOUDLY
// (never silently passes) — false negatives (missing a real untagged call)
// are the failure mode being guarded against, so the scanner is written to
// over-flag rather than under-flag.
func TestTierForSource_EveryGenerateCallIsTagged(t *testing.T) {
	for _, a := range allowedStrongSources {
		if strings.TrimSpace(a.reason) == "" {
			t.Fatalf("allowedStrongSources entry %q has no reason — every allowlist entry must name why it stays strong", a.tag)
		}
	}
	seen := map[string]bool{}
	for _, a := range allowedStrongSources {
		if seen[a.tag] {
			t.Fatalf("allowedStrongSources has a duplicate entry for %q", a.tag)
		}
		seen[a.tag] = true
	}

	root := repoRoot(t)
	sc := newSourceScanner()
	var files []scannedFile
	for _, dir := range []string{"internal", "cmd"} {
		files = append(files, walkGoFiles(t, root, filepath.Join(root, dir))...)
	}

	// Pass 1: collect every package-level const across the whole corpus, so
	// pass 2 can resolve a tag identifier defined in any package (e.g.
	// prompts.MemoryReviseBeliefs referenced from internal/memory).
	for _, f := range files {
		sc.collectConsts(f)
	}

	// Pass 2: find every Generate(...) call and classify its tag.
	var failures []string
	totalCalls := 0
	for _, f := range files {
		if skipGenerateCallFiles[f.relPath] {
			continue
		}
		fileFailures, fileCalls := sc.scanFile(f)
		failures = append(failures, fileFailures...)
		totalCalls += fileCalls
	}

	// Coverage floor: a scan that silently walked zero files (wrong roots, a
	// repoRoot() miscalculation, internal/ or cmd/ moved in a refactor) finds
	// zero Generate calls and therefore reports zero failures — passing for
	// exactly the wrong reason. Assert a lower bound on what the walk
	// actually found, so a collapse in coverage fails loudly instead of
	// reading as "no problems." See minGoFilesWalked/minGenerateCallsClassified.
	if len(files) < minGoFilesWalked {
		t.Fatalf("walked only %d non-test .go files under internal/ and cmd/, want at least %d — the scan may be looking at the wrong roots (repoRoot() resolved to %q)", len(files), minGoFilesWalked, root)
	}
	if totalCalls < minGenerateCallsClassified {
		t.Fatalf("classified only %d Generate call sites, want at least %d — a scan that finds too few calls is as broken as one that finds none: it may be silently missing whole packages", totalCalls, minGenerateCallsClassified)
	}

	for _, f := range failures {
		t.Error(f)
	}
	t.Logf("tier scan: walked %d files, classified %d Generate call sites", len(files), totalCalls)
}

// minGoFilesWalked and minGenerateCallsClassified are coverage floors, not
// exact counts: at the time this test was written, walking internal/ and
// cmd/ found 376 non-test .go files and classified 47 Generate call sites
// (logged by the test itself on every run — t.Logf above). Both floors sit
// comfortably below those measured numbers (300 and 30) so ordinary code
// growth (a new pipeline, a new prompt) never trips them, but a walk that
// silently covers nothing or almost nothing — wrong roots, a moved
// directory, a broken repoRoot() — fails loudly instead of reporting a false
// "no problems found" (exactly what happened pointing the roots at docs/
// during this test's own review: 0 files, 0 calls, PASS in 0.01s). Raise
// these deliberately (with a note here, and the new measured numbers) once
// real growth pushes the logged counts close to the floor; never lower them
// just to make a failing run pass.
const (
	minGoFilesWalked           = 300
	minGenerateCallsClassified = 30
)

// repoRoot resolves the repository root relative to this test file, so the
// scan works regardless of the working directory `go test` was invoked from.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed resolving this test file's path")
	}
	// internal/digest/tier_scan_test.go -> repo root is two directories up.
	root := filepath.Join(filepath.Dir(thisFile), "..", "..")
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		t.Fatalf("resolved repo root %q does not contain go.mod: %v", root, err)
	}
	return root
}

type scannedFile struct {
	relPath string // e.g. "internal/memory/pipeline.go", for error messages and the skip list
	file    *ast.File
	fset    *token.FileSet
	pkg     string
}

// walkGoFiles parses every non-test .go file under dir (recursively),
// tagging each with its package name (the "package X" clause, not the import
// path) and its path relative to root (for error messages and the
// skipGenerateCallFiles lookup).
func walkGoFiles(t *testing.T, root, dir string) []scannedFile {
	t.Helper()
	var out []scannedFile
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		fset := token.NewFileSet()
		f, perr := parser.ParseFile(fset, path, nil, 0)
		if perr != nil {
			t.Fatalf("parsing %s: %v", path, perr)
		}
		rel, rerr := filepath.Rel(root, path)
		if rerr != nil {
			rel = path
		}
		out = append(out, scannedFile{relPath: rel, file: f, fset: fset, pkg: f.Name.Name})
		return nil
	})
	if err != nil {
		t.Fatalf("walking %s: %v", dir, err)
	}
	return out
}

// sourceScanner holds the cross-file state the property scan needs: every
// package-level const's raw value expression, keyed by package name (the
// "package X" clause — this repo does not alias imports for digest/prompts/
// memory/etc., so matching a selector's package identifier text against this
// map is safe; see the doc comment on resolveTagExprToStrings).
type sourceScanner struct {
	consts map[string]map[string]constRaw
}

type constRaw struct {
	expr ast.Expr
	pkg  string
}

func newSourceScanner() *sourceScanner {
	return &sourceScanner{consts: map[string]map[string]constRaw{}}
}

func (sc *sourceScanner) collectConsts(f scannedFile) {
	for _, decl := range f.file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, name := range vs.Names {
				if name.Name == "_" || i >= len(vs.Values) {
					continue
				}
				if sc.consts[f.pkg] == nil {
					sc.consts[f.pkg] = map[string]constRaw{}
				}
				sc.consts[f.pkg][name.Name] = constRaw{expr: vs.Values[i], pkg: f.pkg}
			}
		}
	}
}

// resolveConst resolves a package-level const to its string value, following
// `const A = B` and `const A = otherpkg.B` chains. seen guards against a
// (would-be malformed) cycle.
func (sc *sourceScanner) resolveConst(pkg, name string, seen map[string]bool) (string, bool) {
	key := pkg + "." + name
	if seen[key] {
		return "", false
	}
	seen[key] = true
	raw, ok := sc.consts[pkg][name]
	if !ok {
		return "", false
	}
	switch e := raw.expr.(type) {
	case *ast.BasicLit:
		if e.Kind != token.STRING {
			return "", false
		}
		v, err := strconv.Unquote(e.Value)
		if err != nil {
			return "", false
		}
		return v, true
	case *ast.Ident:
		return sc.resolveConst(pkg, e.Name, seen)
	case *ast.SelectorExpr:
		xIdent, ok := e.X.(*ast.Ident)
		if !ok {
			return "", false
		}
		return sc.resolveConst(xIdent.Name, e.Sel.Name, seen)
	}
	return "", false
}

// isWithSourceCall reports whether call is `digest.WithSource(...)`, or bare
// `WithSource(...)` when the call site is already inside package digest.
func isWithSourceCall(call *ast.CallExpr, pkg string) bool {
	switch fn := call.Fun.(type) {
	case *ast.Ident:
		return pkg == "digest" && fn.Name == "WithSource"
	case *ast.SelectorExpr:
		xIdent, ok := fn.X.(*ast.Ident)
		return ok && xIdent.Name == "digest" && fn.Sel.Name == "WithSource"
	}
	return false
}

// resolveTagExprToStrings resolves a WithSource tag expression to the set of
// literal strings it can evaluate to. Beyond literals and consts, this
// carries exactly two hand-verified exceptions for the only two call sites
// in the repo (as of fix wave 4 task 6) where the tag travels through a
// local variable or parameter rather than a literal/const:
//
//   - internal/memory/pipeline.go's extractBatch: `source` is the third
//     return value of batchPrompts, which returns either extractSource
//     ("memory.extract_episodes") or extractBatchSource
//     ("memory.extract_episodes_batch") depending on batch size.
//   - internal/ideas/email_digest.go's mineStreamTopics: `promptID` is a
//     parameter passed "ideas.digest_email" (email_digest.go) or
//     "ideas.digest_jira" (jira_digest.go) by its two callers.
//
// A future dynamic call site this function doesn't recognize resolves to
// ok=false, which the caller treats as a hard failure (over-flag, never
// under-flag) rather than silently passing — extend this function (or, if
// there is a real reason to leave the tag strong, add to
// allowedStrongSources) rather than loosen the failure into a skip.
func (sc *sourceScanner) resolveTagExprToStrings(expr ast.Expr, pkg, funcName string) ([]string, bool) {
	switch e := expr.(type) {
	case *ast.BasicLit:
		if e.Kind != token.STRING {
			return nil, false
		}
		v, err := strconv.Unquote(e.Value)
		if err != nil {
			return nil, false
		}
		return []string{v}, true
	case *ast.Ident:
		if v, ok := sc.resolveConst(pkg, e.Name, map[string]bool{}); ok {
			return []string{v}, true
		}
		if e.Name == "source" && funcName == "extractBatch" {
			return []string{"memory.extract_episodes", "memory.extract_episodes_batch"}, true
		}
		if e.Name == "promptID" && funcName == "mineStreamTopics" {
			return []string{"ideas.digest_email", "ideas.digest_jira"}, true
		}
		return nil, false
	case *ast.SelectorExpr:
		xIdent, ok := e.X.(*ast.Ident)
		if !ok {
			return nil, false
		}
		if v, ok := sc.resolveConst(xIdent.Name, e.Sel.Name, map[string]bool{}); ok {
			return []string{v}, true
		}
		return nil, false
	}
	return nil, false
}

// extractTagExpr looks at Generate's first (context) argument and reports
// the WithSource tag expression feeding it, if any: either the argument is
// itself a WithSource(...) call, or it is an identifier previously bound by
// `x := digest.WithSource(...)` (or `x := WithSource(...)` within package
// digest) earlier in the same function body (localVars).
func extractTagExpr(ctxArg ast.Expr, pkg string, localVars map[string]ast.Expr) (ast.Expr, bool) {
	if call, ok := ctxArg.(*ast.CallExpr); ok && isWithSourceCall(call, pkg) && len(call.Args) == 2 {
		return call.Args[1], true
	}
	if ident, ok := ctxArg.(*ast.Ident); ok {
		if tagExpr, found := localVars[ident.Name]; found {
			return tagExpr, true
		}
	}
	return nil, false
}

// scanFile walks every FuncDecl in f (and any nested func literals) looking
// for Generate(ctx, systemPrompt, userMessage, sessionID) calls (exactly the
// digest.Generator signature — verified against the concrete Generate
// implementations, no other 4-arg "Generate" method exists in the repo) and
// classifying each one. Returns human-readable failure strings (empty means
// every call in this file passed) plus the number of Generate calls found in
// this file, whether or not they passed — the caller uses that count for the
// coverage floor (see minGenerateCallsClassified). Per-call classification
// and tag-expression resolution are split into their own functions
// (recordWithSourceBinding, classifyGenerateCall, classifyTagCandidates) to
// keep this function's own cyclomatic complexity down (gocyclo).
func (sc *sourceScanner) scanFile(f scannedFile) ([]string, int) {
	var failures []string
	found := 0
	for _, decl := range f.file.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Body == nil {
			continue
		}
		localVars := map[string]ast.Expr{}
		funcName := fd.Name.Name
		ast.Inspect(fd.Body, func(n ast.Node) bool {
			switch stmt := n.(type) {
			case *ast.AssignStmt:
				recordWithSourceBinding(stmt, f.pkg, localVars)
			case *ast.CallExpr:
				if !isGenerateCall(stmt) {
					return true
				}
				found++
				failures = append(failures, sc.classifyGenerateCall(stmt, f, funcName, localVars)...)
			}
			return true
		})
	}
	return failures, found
}

// isGenerateCall reports whether stmt is a `Generate(ctx, systemPrompt,
// userMessage, sessionID)` call — a method named Generate with exactly 4
// arguments, matching the digest.Generator signature.
func isGenerateCall(stmt *ast.CallExpr) bool {
	sel, ok := stmt.Fun.(*ast.SelectorExpr)
	return ok && sel.Sel.Name == "Generate" && len(stmt.Args) == 4
}

// recordWithSourceBinding notes `x := digest.WithSource(_, tagExpr)` (or
// bare `x := WithSource(_, tagExpr)` within package digest itself)
// assignments into localVars, so a later Generate(x, ...) call in the same
// function can resolve x back to its tag expression.
func recordWithSourceBinding(stmt *ast.AssignStmt, pkg string, localVars map[string]ast.Expr) {
	if len(stmt.Lhs) != 1 || len(stmt.Rhs) != 1 {
		return
	}
	call, ok := stmt.Rhs[0].(*ast.CallExpr)
	if !ok || !isWithSourceCall(call, pkg) || len(call.Args) != 2 {
		return
	}
	ident, ok := stmt.Lhs[0].(*ast.Ident)
	if !ok || ident.Name == "_" {
		return
	}
	localVars[ident.Name] = call.Args[1]
}

// classifyGenerateCall inspects one Generate(...) call site's context
// argument and returns every failure it produces (untagged, an unresolvable
// tag expression, or a resolved tag that routes strong without an
// allowedStrongSources entry) — empty means the call passed.
func (sc *sourceScanner) classifyGenerateCall(stmt *ast.CallExpr, f scannedFile, funcName string, localVars map[string]ast.Expr) []string {
	pos := f.fset.Position(stmt.Pos())
	loc := f.relPath + ":" + strconv.Itoa(pos.Line)

	tagExpr, tagged := extractTagExpr(stmt.Args[0], f.pkg, localVars)
	if !tagged {
		return []string{loc + " calls Generate with an untagged context — add digest.WithSource(ctx, \"<tag>\")"}
	}
	candidates, ok := sc.resolveTagExprToStrings(tagExpr, f.pkg, funcName)
	if !ok {
		return []string{loc + " tags Generate with an expression this scan cannot resolve to a literal string — extend resolveTagExprToStrings or use a plain string literal"}
	}
	return classifyTagCandidates(candidates, loc)
}

// classifyTagCandidates checks each resolved tag string against
// TierForSource and, for one that routes strong, against
// allowedStrongSources — returning one failure string per unacknowledged
// strong tag.
func classifyTagCandidates(candidates []string, loc string) []string {
	var failures []string
	for _, tag := range candidates {
		if TierForSource(tag) == TierLight {
			continue
		}
		if !seenInAllowlist(tag) {
			failures = append(failures, loc+" tags source "+strconv.Quote(tag)+" which routes strong by TierForSource's default arm and is not acknowledged in allowedStrongSources — add it with a reason, or route it light")
		}
	}
	return failures
}

func seenInAllowlist(tag string) bool {
	for _, a := range allowedStrongSources {
		if a.tag == tag {
			return true
		}
	}
	return false
}
