// Package terminal reads Claude Code session transcripts for the embedded
// terminal sessions (pure: no DB, no network).
package terminal

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"path/filepath"
	"regexp"
	"strings"
	"unicode/utf8"
)

// ErrNoTranscript means Claude Code has not written a transcript for the
// session (yet): not an error worth surfacing to the owner.
var ErrNoTranscript = errors.New("no transcript for session")

var uuidRe = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)

// FindTranscript locates Claude Code's transcript for a session id. The id is
// generated by Watchtower (a UUID), so a glob over the project folders finds
// it without re-deriving Claude Code's folder-name escaping.
func FindTranscript(claudeDir, sessionID string) (string, error) {
	if !uuidRe.MatchString(sessionID) {
		return "", fmt.Errorf("not a session id: %q", sessionID)
	}
	root, err := filepath.EvalSymlinks(filepath.Join(claudeDir, "projects"))
	if errors.Is(err, fs.ErrNotExist) {
		return "", fmt.Errorf("%w %s", ErrNoTranscript, sessionID)
	}
	if err != nil {
		return "", fmt.Errorf("claude projects dir: %w", err)
	}
	matches, _ := filepath.Glob(filepath.Join(root, "*", sessionID+".jsonl"))
	for _, m := range matches {
		resolved, err := filepath.EvalSymlinks(m)
		if err == nil && strings.HasPrefix(resolved, root+string(filepath.Separator)) {
			return resolved, nil
		}
	}
	return "", fmt.Errorf("%w %s", ErrNoTranscript, sessionID)
}

type transcriptLine struct {
	Type    string `json:"type"`
	IsMeta  bool   `json:"isMeta"`
	Message struct {
		Role    string          `json:"role"`
		Content json.RawMessage `json:"content"`
	} `json:"message"`
}

// OwnerMessages returns the owner's typed text, oldest first, joined by
// newlines and capped at capChars runes: meta lines, slash-command echoes,
// tool results and assistant text are left out.
func OwnerMessages(r io.Reader, capChars int) (string, error) {
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 8*1024*1024)
	var parts []string
	total := 0
	for sc.Scan() && total < capChars {
		var l transcriptLine
		if json.Unmarshal(sc.Bytes(), &l) != nil || l.Type != "user" || l.IsMeta || l.Message.Role != "user" {
			continue
		}
		text := strings.TrimSpace(ownerText(l.Message.Content))
		if text == "" || strings.HasPrefix(text, "<") {
			continue
		}
		parts = append(parts, text)
		total += utf8.RuneCountInString(text) + 1
	}
	if err := sc.Err(); err != nil {
		return "", fmt.Errorf("reading transcript: %w", err)
	}
	return truncateRunes(strings.Join(parts, "\n"), capChars), nil
}

func ownerText(raw json.RawMessage) string {
	var s string
	if json.Unmarshal(raw, &s) == nil {
		return s
	}
	var blocks []struct{ Type, Text string }
	if json.Unmarshal(raw, &blocks) != nil {
		return ""
	}
	var out []string
	for _, b := range blocks {
		if b.Type == "text" {
			out = append(out, b.Text)
		}
	}
	return strings.Join(out, "\n")
}

func truncateRunes(s string, n int) string {
	if utf8.RuneCountInString(s) <= n {
		return s
	}
	return string([]rune(s)[:n])
}
