// Package terminal reads Claude Code session transcripts for the embedded
// terminal sessions (pure: no DB, no network).
package terminal

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"path/filepath"
	"regexp"
	"strings"
	"unicode/utf8"
)

// ErrNoTranscript means Claude Code has not written a transcript for the
// session (yet): not an error worth surfacing to the owner.
var ErrNoTranscript = errors.New("no transcript for session")

var uuidRe = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)

// IsSessionID reports whether id is a lowercase canonical UUID, the only
// form a terminal_sessions row may store (the Desktop interpolates it into a
// shell command; its twin is `TerminalLaunch.isValidSessionID`).
func IsSessionID(id string) bool { return uuidRe.MatchString(id) }

// FindTranscript locates Claude Code's transcript for a session id. The id is
// generated by Watchtower (a UUID), so a glob over the project folders finds
// it without re-deriving Claude Code's folder-name escaping.
func FindTranscript(claudeDir, sessionID string) (string, error) {
	if !uuidRe.MatchString(sessionID) {
		return "", fmt.Errorf("not a session id: %q", sessionID)
	}
	if claudeDir == "" {
		return "", errors.New("claude config dir unknown")
	}
	root, err := filepath.EvalSymlinks(filepath.Join(claudeDir, "projects"))
	if errors.Is(err, fs.ErrNotExist) {
		return "", fmt.Errorf("%w %s", ErrNoTranscript, sessionID)
	}
	if err != nil {
		return "", fmt.Errorf("claude projects dir: %w", err)
	}
	matches, _ := filepath.Glob(filepath.Join(root, "*", sessionID+".jsonl"))
	for _, m := range matches {
		resolved, err := filepath.EvalSymlinks(m)
		if err == nil && strings.HasPrefix(resolved, root+string(filepath.Separator)) {
			return resolved, nil
		}
	}
	return "", fmt.Errorf("%w %s", ErrNoTranscript, sessionID)
}

type transcriptLine struct {
	Type    string `json:"type"`
	IsMeta  bool   `json:"isMeta"`
	Message struct {
		Role    string          `json:"role"`
		Content json.RawMessage `json:"content"`
	} `json:"message"`
}

// maxTranscriptLine bounds one transcript line read into memory; a longer one
// (a base64 image inside a tool result) is skipped, never an error.
var maxTranscriptLine = 8 * 1024 * 1024

// OwnerMessages returns the owner's typed text, oldest first, joined by
// newlines and capped at capChars runes: meta lines, slash-command echoes,
// tool results and assistant text are left out.
func OwnerMessages(r io.Reader, capChars int) (string, error) {
	br := bufio.NewReaderSize(r, 64*1024)
	var parts []string
	total := 0
	for total < capChars {
		line, err := readLine(br, maxTranscriptLine)
		if err != nil && err != io.EOF {
			return "", fmt.Errorf("reading transcript: %w", err)
		}
		if line != nil {
			if text := ownerLineText(line); text != "" {
				parts = append(parts, text)
				total += utf8.RuneCountInString(text) + 1
			}
		}
		if err == io.EOF {
			break
		}
	}
	return truncateRunes(strings.Join(parts, "\n"), capChars), nil
}

// readLine returns the next line, or nil when it is longer than limit (the
// rest of it is consumed). err is io.EOF with the final line, if any.
func readLine(br *bufio.Reader, limit int) ([]byte, error) {
	var buf []byte
	tooLong := false
	for {
		chunk, isPrefix, err := br.ReadLine()
		if err != nil {
			if tooLong || len(buf) == 0 {
				return nil, err
			}
			return buf, err
		}
		if !tooLong {
			buf = append(buf, chunk...)
			if len(buf) > limit {
				tooLong, buf = true, nil
			}
		}
		if !isPrefix {
			if tooLong {
				return nil, nil
			}
			return buf, nil
		}
	}
}

func ownerLineText(line []byte) string {
	var l transcriptLine
	if json.Unmarshal(line, &l) != nil || l.Type != "user" || l.IsMeta || l.Message.Role != "user" {
		return ""
	}
	text := strings.TrimSpace(ownerText(l.Message.Content))
	if strings.HasPrefix(text, "<") {
		return ""
	}
	return text
}

func ownerText(raw json.RawMessage) string {
	var s string
	if json.Unmarshal(raw, &s) == nil {
		return s
	}
	var blocks []struct{ Type, Text string }
	if json.Unmarshal(raw, &blocks) != nil {
		return ""
	}
	var out []string
	for _, b := range blocks {
		if b.Type == "text" {
			out = append(out, b.Text)
		}
	}
	return strings.Join(out, "\n")
}

func truncateRunes(s string, n int) string {
	if utf8.RuneCountInString(s) <= n {
		return s
	}
	return string([]rune(s)[:n])
}
