package db

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// desktopTestSchemaPath is the Swift file the Desktop tests build their
// database from (TestDatabase.schema).
var desktopTestSchemaPath = filepath.Join("..", "..", "WatchtowerDesktop", "Tests", "Support", "TestDatabase+Schema.swift")

// TestDesktopTestSchema keeps the Swift tests on the production schema: the
// Swift file is generated from the DDL a fresh Open() migrates to, and this
// test fails when the two diverge. A hand-kept copy drifted (dropped tables
// still present, columns missing), so Swift writers passed tests against a
// schema production would reject. After a migration, regenerate with:
//
//	go test ./internal/db/ -run TestDesktopTestSchema -update
func TestDesktopTestSchema(t *testing.T) {
	d, err := Open(filepath.Join(t.TempDir(), "desktop.db"))
	require.NoError(t, err)
	defer d.Close()

	got := renderDesktopTestSchema(t, d)

	if *updateGolden {
		require.NoError(t, os.WriteFile(desktopTestSchemaPath, []byte(got), 0o644))
		t.Logf("wrote %s (%d bytes)", desktopTestSchemaPath, len(got))
		return
	}

	want, err := os.ReadFile(desktopTestSchemaPath)
	require.NoError(t, err)
	if got != string(want) {
		t.Errorf("%s is stale — regenerate with `go test ./internal/db/ -run TestDesktopTestSchema -update`\n--- file\n+++ migrated\n%s",
			desktopTestSchemaPath, firstDiff(string(want), got))
	}
}

// createRe matches the head of a stored CREATE statement, up to the object name.
var createRe = regexp.MustCompile(`^(CREATE (?:TABLE|VIRTUAL TABLE|UNIQUE INDEX|INDEX|TRIGGER|VIEW) )`)

// renderDesktopTestSchema emits every user-defined object of d as one Swift
// raw string: tables (FTS shadow tables left to their virtual table), then
// views, indexes and triggers, each group in creation order.
func renderDesktopTestSchema(t *testing.T, d *DB) string {
	t.Helper()
	ddl := queryStrings(t, d, `
		SELECT m.sql FROM sqlite_master m
		LEFT JOIN pragma_table_list tl ON tl.schema = 'main' AND tl.name = m.name
		WHERE m.sql IS NOT NULL
		  AND m.name NOT LIKE 'sqlite_%'
		  AND m.tbl_name != 'goose_db_version'
		  AND COALESCE(tl.type, '') != 'shadow'
		ORDER BY CASE m.type WHEN 'table' THEN 0 WHEN 'view' THEN 1 WHEN 'index' THEN 2 ELSE 3 END, m.rowid`)

	var b strings.Builder
	b.WriteString(`// Code generated by TestDesktopTestSchema (internal/db/desktop_test_schema_test.go). DO NOT EDIT.
// Regenerate after a migration: go test ./internal/db/ -run TestDesktopTestSchema -update

/// The watchtower schema exactly as a fresh ` + "`db.Open`" + ` migrates it, so Swift
/// tests run against the production tables, columns, CHECKs and foreign keys.
extension TestDatabase {
    package static let schema = #"""
`)
	for _, stmt := range ddl {
		// sqlite_master drops IF NOT EXISTS; restore it so a test can re-run
		// the schema to recreate tables it dropped.
		stmt = createRe.ReplaceAllString(strings.TrimSpace(stmt), "${1}IF NOT EXISTS ")
		lines := strings.Split(stmt, "\n")
		for i, line := range lines {
			lines[i] = strings.TrimRight(line, " \t")
		}
		b.WriteString(strings.Join(lines, "\n"))
		b.WriteString(";\n")
	}
	b.WriteString(`"""#
}
`)
	return b.String()
}
